server:
  port: 8190
  servlet:
    context-path: /market-carts
integrations:
  product-service:
    url: http://localhost:8189/market-core
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
cart-service:
  cart-prefix: market_cart_
spring:
  redis:
    port: 6379
    host: 127.0.0.1