server:
  port: 8188
  servlet:
    context-path: /market-auth

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:auth;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

jwt:
  secret: bgtd6pg43tHFsa467yBFDgw4332ytJgfD4s32FSAPVF4t.
  lifetime: 36000000
